name: CI
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.java'
      - '**.gradle'
      - 'brut.apktool/apktool-lib/src/main/resources/**'
      - 'brut.apktool/apktool-lib/src/test/**'
      - '.github/workflows/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BINARY_PATH: brut.apktool/apktool-lib/src/main/resources/prebuilt

jobs:
  analyze-windows-aapt:
    runs-on: windows-latest
    strategy:
      matrix:
        file: [ aapt.exe, aapt_64.exe, aapt2.exe, aapt2_64.exe ]
    steps:
      - uses: actions/checkout@v3
      - name: Verify Executable
        run: ${{ env.BINARY_PATH }}/windows/${{ matrix.file }} version
      - name: Output Static
        run: ldd ${{ env.BINARY_PATH }}/windows/${{ matrix.file }} || true
        
  upload-artifact:
    runs-on: ubuntu-latest
    name: Build apktool.jar
    if: github.repository == 'b4byhuey/Apktool' && github.ref == 'refs/heads/master' 
    needs:
      - analyze-windows-aapt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build shadowJar proguard
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: apktool.jar
          path: brut.apktool/apktool-cli/build/libs/apktool-*-small.jar  
